-- custom_maps.lua — list of ICAOs the user added by hand to the "Map"
-- dropdown, persisted across DCS sessions as a plain Lua file at
-- <Saved Games>\DCS\actual-metar\custom_icaos.lua (same style dcs-sms uses
-- for its own settings files, e.g. me_hotkeys.lua).
--
-- ICAOs added this way have no known real timezone (there's no way to
-- guess where a hand-typed airport is) — they're saved with
-- std_offset_h=0, rule="none" (UTC) as a reasonable default; the "Map"
-- time mode for one of these will show the current UTC time, and the user
-- can hand-edit the file if they know the real zone.

local paths = require("actual_metar.paths")

local M = {}

local FILE_NAME = "custom_icaos.lua"

local function file_path()
    local dir = paths.own_dir()
    if not dir then return nil end
    return dir .. FILE_NAME
end

function M.load()
    local path = file_path()
    if not path then return {} end
    local chunk = loadfile(path)
    if not chunk then return {} end
    local ok, result = pcall(chunk)
    if ok and type(result) == "table" then return result end
    return {}
end

local function serialize(list)
    local parts = { "-- generated by ACTUAL METAR - do not edit while the editor is open\nreturn {\n" }
    for _, e in ipairs(list) do
        parts[#parts + 1] = string.format(
            "  { name = %q, icao = %q, std_offset_h = %s, rule = %q },\n",
            e.name or e.icao, e.icao, tostring(e.std_offset_h or 0), e.rule or "none")
    end
    parts[#parts + 1] = "}\n"
    return table.concat(parts)
end

function M.save(list)
    local path = file_path()
    if not path then return false, "could not resolve Saved Games\\DCS\\" end
    local f, err = io.open(path, "w")
    if not f then return false, tostring(err) end
    f:write(serialize(list))
    f:close()
    return true
end

-- add(icao, custom_name) -> ok, list_or_error. custom_name is optional; if
-- omitted or blank, "Custom (ICAO)" is used by default.
function M.add(icao, custom_name)
    icao = tostring(icao or ""):upper():gsub("%s+", "")
    if not icao:match("^[A-Z0-9]+$") or #icao < 3 or #icao > 4 then
        return false, "Invalid ICAO: " .. tostring(icao)
    end
    local list = M.load()
    for _, e in ipairs(list) do
        if e.icao == icao then return false, "that ICAO is already in the list" end
    end
    custom_name = tostring(custom_name or ""):gsub("^%s+", ""):gsub("%s+$", "")
    if custom_name == "" then custom_name = "Custom (" .. icao .. ")" end
    table.insert(list, {
        name = custom_name,
        icao = icao,
        std_offset_h = 0,
        rule = "none",
    })
    local ok, err = M.save(list)
    if not ok then return false, err end
    return true, list
end

-- remove(icao) -> ok, list_or_error
function M.remove(icao)
    icao = tostring(icao or ""):upper()
    local list = M.load()
    local new_list, removed = {}, false
    for _, e in ipairs(list) do
        if e.icao == icao then
            removed = true
        else
            new_list[#new_list + 1] = e
        end
    end
    if not removed then return false, "that ICAO isn't in the custom list" end
    local ok, err = M.save(new_list)
    if not ok then return false, err end
    return true, new_list
end

return M
